on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
        with:
          repository: radekn/turn-based-mech-battle
          token: ${{ secrets.CHECKOUT_ACCESS_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build the project
        run: pnpm run build
      - uses: actions/upload-pages-artifact@v1
        with:
          path: dist/
      - uses: actions/deploy-pages@v2
